version: '3'
services:
  arangodb:
    image: "arangodb/arangodb:latest"
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    volumes:
      - /var/lib/arangodb3:/var/lib/arangodb3
